version: "3.7"
services:

  #PHP service
  ez-games-app:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: ez-games-app
    container_name: ez-games-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: ./php/config/local.ini
        target: /usr/local/etc/php/conf.d/local.ini
    networks:
      - ez-games-network


  #Mysql service
  ez-games-db:
    image: mysql:5.7
    container_name: ez-games-db
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: ./mysql/
        target: /var/www/
    environment:
      MYSQL_DATABASE: ez-games
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - ez-games-network


  #Nginx service
  ez-games-webserver:
    image: nginx:alpine
    container_name: ez-games-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d/
    networks:
      - ez-games-network

  ez-games-node:
    build:
      context: .
      dockerfile: node/Dockerfile
    image: node:15.6-alpine
    container_name: ez-games-node
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /usr/app
    networks:
      - ez-games-network

#Docker Networks
networks:
  ez-games-network:
    driver: bridge
